# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4fb794c0ffd6d267bb3bbad3e481fcca75c2b06a85e34b5e40973794749c5fff6132fb1696a9301cf841d760b85f6fbad6dd20fc4cc45c8c5523ac39b73df3ea

test:
  secret_key_base: 15d9dc604b9a138ee10e871cb0995ba66f709c67e912dca3e7c166c092a5d0d2dc50d0a5fff0f6952aaa80fdc5499047786c575006db45380f79bc62583e4d47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
